# Creating wildfire dataset for any country using global satellite data #
## We are using country Nepal as our target country  in this example ##

## Data Collection ##
- Please Visit https://firms.modaps.eosdis.nasa.gov/download/ to download both MODIS (2000-2020) and VIIRS (2012-2020) datasets based on each country wildfire data
  - MODIS - https://firms.modaps.eosdis.nasa.gov/country/
  - VIIRS - https://firms.modaps.eosdis.nasa.gov/country/
  - Active Fire (24 Hours, 48 Hours, 7 days)-  https://firms.modaps.eosdis.nasa.gov/usfs/active_fire/

<div style="max-width:400px;">
    <img src="https://github.com/prodramp/wildfire/blob/main/images/disclaimer.png?raw=true" size="400px"/>
</div>

In [1]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
import random
InteractiveShell.ast_node_interactivity = "all"
import os
from datetime import datetime
import plotly.express as px
import glob
from tqdm import tqdm
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
!ls -l ../

total 8
-rw-r--r--   1 avkash  staff  511 Mar 26 12:49 README.md
drwxr-xr-x@ 15 avkash  staff  480 Mar 26 13:26 dataset
drwxr-xr-x   6 avkash  staff  192 Mar 26 08:03 images
drwxr-xr-x@  5 avkash  staff  160 Mar 25 15:32 wildfire-data
drwxr-xr-x   8 avkash  staff  256 Mar 26 12:47 wildfire-data-streamlit
drwxr-xr-x@ 24 avkash  staff  768 Mar 25 15:29 zips_modis
drwxr-xr-x@ 13 avkash  staff  416 Mar 25 15:26 zips_viirs

In [3]:
! ls -lh ../wildfire-data

total 0
drwxr-xr-x@ 24 avkash  staff   768B Mar 25 15:28 modis
drwxr-xr-x@ 13 avkash  staff   416B Mar 25 15:26 viirs-snpp

In [4]:
! ls -lh ../wildfire-data/modis

total 0
drwxr-xr-x@ 165 avkash  staff   5.2K Feb 12  2019 2000
drwxr-xr-x@ 199 avkash  staff   6.2K Nov 16 09:06 2001
drwxr-xr-x@ 201 avkash  staff   6.3K Nov 16 09:06 2002
drwxr-xr-x@ 206 avkash  staff   6.4K Nov 16 09:06 2003
drwxr-xr-x@ 204 avkash  staff   6.4K Nov 16 09:06 2004
drwxr-xr-x@ 210 avkash  staff   6.6K Nov 16 09:06 2005
drwxr-xr-x@ 204 avkash  staff   6.4K Nov 16 09:06 2006
drwxr-xr-x@ 210 avkash  staff   6.6K Nov 16 09:06 2007
drwxr-xr-x@ 207 avkash  staff   6.5K Nov 16 09:06 2008
drwxr-xr-x@ 207 avkash  staff   6.5K Nov 16 09:06 2009
drwxr-xr-x@ 205 avkash  staff   6.4K Nov 16 09:06 2010
drwxr-xr-x@ 203 avkash  staff   6.3K Nov 16 09:06 2011
drwxr-xr-x@ 206 avkash  staff   6.4K Nov 16 09:06 2012
drwxr-xr-x@ 209 avkash  staff   6.5K Nov 16 09:06 2013
drwxr-xr-x@ 206 avkash  staff   6.4K Nov 16 09:06 2014
drwxr-xr-x@ 211 avkash  staff   6.6K Nov 16 09:06 2015
drwxr-xr-x@ 209 avkash  staff   6.5K Nov 16 09:06 2016
drwxr-xr-x@ 207 avkash  staff   6.5K Nov 16 09:06 2017
drwxr-xr-x@ 208 avkash  staff   6.5K Nov 16 09:06 2018
drwxr-xr-x@ 204 avkash  staff   6.4K Nov 16 09:06 2019
drwxr-xr-x@ 213 avkash  staff   6.7K Nov 16 09:06 2020

In [5]:
! ls -lh ../wildfire-data/viirs-snpp

total 0
drwxr-xr-x@ 222 avkash  staff   6.9K Nov 16 09:04 2012
drwxr-xr-x@ 225 avkash  staff   7.0K Nov 16 09:04 2013
drwxr-xr-x@ 216 avkash  staff   6.8K Nov 16 09:04 2014
drwxr-xr-x@ 218 avkash  staff   6.8K Nov 16 09:04 2015
drwxr-xr-x@ 222 avkash  staff   6.9K Nov 16 09:04 2016
drwxr-xr-x@ 218 avkash  staff   6.8K Nov 16 09:04 2017
drwxr-xr-x@ 221 avkash  staff   6.9K Nov 16 09:04 2018
drwxr-xr-x@ 219 avkash  staff   6.8K Nov 16 09:04 2019
drwxr-xr-x@ 220 avkash  staff   6.9K Nov 16 09:04 2020
drwxr-xr-x@ 218 avkash  staff   6.8K Jan 27 05:18 2021

In [6]:
all_csv_files = glob.glob('../wildfire-data/**/*.csv', recursive=True)

In [7]:
all_csv_files

['../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Reunion.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Barbados.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Greenland.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Burundi.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Nepal.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Moldova.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Papua_New_Guinea.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Cook_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Belgium.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Ethiopia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Cuba.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Democratic_Republic_of_the_Congo.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Timor-Leste.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Sint_Maarten.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Mauritania.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Zimbabwe.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Benin.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Aland_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Azerbaijan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Trinidad_and_Tobago.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Dem_Rep_Korea.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Niue.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Jersey.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Gabon.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_United_States.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Switzerland.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Sao_Tome_and_Principe.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Syria.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Nigeria.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Libya.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Burkina_Faso.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Senegal.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Botswana.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Belize.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Tonga.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Norway.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Mexico.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Comoros.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Slovakia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Slovenia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Martinique.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Guatemala.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Antigua_and_Barbuda.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Iran.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Hong_Kong.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Saint_Vincent_and_the_Grenadines.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Luxembourg.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Dominican_Republic.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Heard_I_and_McDonald_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Faeroe_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Grenada.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Ecuador.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Brunei_Darussalam.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Venezuela.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Bangladesh.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_The_Gambia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Jordan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Argentina.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Malawi.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Kenya.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Bulgaria.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Samoa.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Pakistan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Ghana.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Lesotho.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Bhutan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_China.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Czech_Republic.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Namibia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Jamaica.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Hungary.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Iceland.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Oman.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Anguilla.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Liberia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Afghanistan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Equatorial_Guinea.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Guyana.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Bolivia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Canada.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Central_African_Republic.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Paraguay.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Guam.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Mongolia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Armenia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Lao_PDR.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Costa_Rica.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Portugal.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Thailand.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Kuwait.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Isle_of_Man.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Dominica.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_France.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Suriname.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Cote_d_Ivoire.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Algeria.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Serbia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_El_Salvador.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Curacao.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_French_Southern_and_Antarctic_Lands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Israel.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Latvia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Estonia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Uganda.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Australia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Guinea-Bissau.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Aruba.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Turkmenistan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Maldives.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Uzbekistan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Tunisia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_South_Africa.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Ukraine.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_New_Zealand.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_South_Sudan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Georgia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Italy.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_British_Virgin_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Bahamas.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Mauritius.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Sweden.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Puerto_Rico.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Philippines.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Albania.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Kazakhstan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Greece.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Republic_of_Korea.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Brazil.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Lebanon.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Netherlands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Palau.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Cameroon.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Turkey.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Eritrea.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_French_Polynesia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Denmark.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_India.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Belarus.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Mali.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Nicaragua.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_United_Arab_Emirates.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Romania.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Panama.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Malaysia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Morocco.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Northern_Mariana_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Vietnam.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Macedonia_Former_Yugoslav_Republic_of.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Uruguay.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Cape_Verde.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Ireland.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Niger.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Solomon_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Turks_and_Caicos_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Tajikistan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Kyrgyzstan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Finland.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Guadeloupe.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Egypt.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Croatia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Malta.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Saint_Kitts_and_Nevis.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Antarctica.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Togo.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Japan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Saint_Pierre_and_Miquelon.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Cyprus.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Chile.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Sierra_Leone.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Cayman_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_United_Kingdom.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Vanuatu.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Tanzania.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Saint_Lucia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Germany.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Falkland_Islands.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Angola.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Cambodia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Djibouti.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Fiji.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Saudi_Arabia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_New_Caledonia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Saint-Martin.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Zambia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Indonesia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Lithuania.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Yemen.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Seychelles.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Colombia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Guernsey.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Qatar.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Mozambique.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Saint_Helena.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Poland.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Singapore.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Sudan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Russian_Federation.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Kosovo.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Taiwan.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Palestine.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Swaziland.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Bosnia_and_Herzegovina.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Honduras.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Chad.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Kiribati.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Montserrat.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Haiti.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Montenegro.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Bahrain.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Rwanda.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Madagascar.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Federated_States_of_Micronesia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Sri_Lanka.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Spain.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Guinea.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_French_Guiana.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Myanmar.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Peru.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Somalia.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Republic_of_Congo.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Austria.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Iraq.csv',
 '../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Mayotte.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Guam.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Venezuela.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Mauritania.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Barbados.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Argentina.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Myanmar.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Azerbaijan.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Somalia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Guatemala.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Hong_Kong.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Latvia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Ethiopia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Austria.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Israel.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Uganda.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Mayotte.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Serbia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Zimbabwe.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Democratic_Republic_of_the_Congo.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Kuwait.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_France.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Republic_of_Congo.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Bahrain.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Sao_Tome_and_Principe.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Switzerland.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Guyana.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Guinea-Bissau.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Cayman_Islands.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_United_Kingdom.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Canada.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Saint-Martin.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Saudi_Arabia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Dominican_Republic.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Northern_Mariana_Islands.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_China.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Luxembourg.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_United_Arab_Emirates.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Bangladesh.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Botswana.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Ghana.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Timor-Leste.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Turks_and_Caicos_Islands.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Kenya.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_The_Gambia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Slovenia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Slovakia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Saint_Vincent_and_the_Grenadines.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Oman.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Saint_Helena.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Germany.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Bhutan.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_French_Polynesia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Martinique.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Cote_d_Ivoire.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Greenland.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Jordan.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Pakistan.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Croatia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Malawi.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Bulgaria.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_South_Sudan.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_New_Zealand.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Trinidad_and_Tobago.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Tonga.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Libya.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Australia.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Syria.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Vanuatu.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Heard_I_and_McDonald_Islands.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Dem_Rep_Korea.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Gabon.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Romania.csv',

In [8]:
len(all_csv_files)

6431

In [9]:
type(all_csv_files)

list

In [10]:
all_nepal_files = list(filter(lambda k: 'Nepal' in k, all_csv_files))

In [11]:
all_nepal_files

['../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Nepal.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Nepal.csv',
 '../wildfire-data/viirs-snpp/2015/viirs-snpp_2015_Nepal.csv',
 '../wildfire-data/viirs-snpp/2012/viirs-snpp_2012_Nepal.csv',
 '../wildfire-data/viirs-snpp/2017/viirs-snpp_2017_Nepal.csv',
 '../wildfire-data/viirs-snpp/2019/viirs-snpp_2019_Nepal.csv',
 '../wildfire-data/viirs-snpp/2021/viirs-snpp_2021_Nepal.csv',
 '../wildfire-data/viirs-snpp/2020/viirs-snpp_2020_Nepal.csv',
 '../wildfire-data/viirs-snpp/2018/viirs-snpp_2018_Nepal.csv',
 '../wildfire-data/viirs-snpp/2016/viirs-snpp_2016_Nepal.csv',
 '../wildfire-data/modis/2013/modis_2013_Nepal.csv',
 '../wildfire-data/modis/2014/modis_2014_Nepal.csv',
 '../wildfire-data/modis/2015/modis_2015_Nepal.csv',
 '../wildfire-data/modis/2012/modis_2012_Nepal.csv',
 '../wildfire-data/modis/2008/modis_2008_Nepal.csv',
 '../wildfire-data/modis/2001/modis_2001_Nepal.csv',
 '../wildfire-data/modis/2006/modis_2006_Nepal.csv',
 '../wildfire-data/modis/2007/modis_2007_Nepal.csv',
 '../wildfire-data/modis/2000/modis_2000_Nepal.csv',
 '../wildfire-data/modis/2009/modis_2009_Nepal.csv',
 '../wildfire-data/modis/2017/modis_2017_Nepal.csv',
 '../wildfire-data/modis/2010/modis_2010_Nepal.csv',
 '../wildfire-data/modis/2019/modis_2019_Nepal.csv',
 '../wildfire-data/modis/2020/modis_2020_Nepal.csv',
 '../wildfire-data/modis/2018/modis_2018_Nepal.csv',
 '../wildfire-data/modis/2011/modis_2011_Nepal.csv',
 '../wildfire-data/modis/2016/modis_2016_Nepal.csv',
 '../wildfire-data/modis/2005/modis_2005_Nepal.csv',
 '../wildfire-data/modis/2002/modis_2002_Nepal.csv',
 '../wildfire-data/modis/2003/modis_2003_Nepal.csv',
 '../wildfire-data/modis/2004/modis_2004_Nepal.csv']

In [12]:
all_nepal_files = list(filter(lambda k: 'Nepal.csv' in k, all_csv_files))

In [13]:
all_nepal_files

['../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Nepal.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Nepal.csv',
 '../wildfire-data/viirs-snpp/2015/viirs-snpp_2015_Nepal.csv',
 '../wildfire-data/viirs-snpp/2012/viirs-snpp_2012_Nepal.csv',
 '../wildfire-data/viirs-snpp/2017/viirs-snpp_2017_Nepal.csv',
 '../wildfire-data/viirs-snpp/2019/viirs-snpp_2019_Nepal.csv',
 '../wildfire-data/viirs-snpp/2021/viirs-snpp_2021_Nepal.csv',
 '../wildfire-data/viirs-snpp/2020/viirs-snpp_2020_Nepal.csv',
 '../wildfire-data/viirs-snpp/2018/viirs-snpp_2018_Nepal.csv',
 '../wildfire-data/viirs-snpp/2016/viirs-snpp_2016_Nepal.csv',
 '../wildfire-data/modis/2013/modis_2013_Nepal.csv',
 '../wildfire-data/modis/2014/modis_2014_Nepal.csv',
 '../wildfire-data/modis/2015/modis_2015_Nepal.csv',
 '../wildfire-data/modis/2012/modis_2012_Nepal.csv',
 '../wildfire-data/modis/2008/modis_2008_Nepal.csv',
 '../wildfire-data/modis/2001/modis_2001_Nepal.csv',
 '../wildfire-data/modis/2006/modis_2006_Nepal.csv',
 '../wildfire-data/modis/2007/modis_2007_Nepal.csv',
 '../wildfire-data/modis/2000/modis_2000_Nepal.csv',
 '../wildfire-data/modis/2009/modis_2009_Nepal.csv',
 '../wildfire-data/modis/2017/modis_2017_Nepal.csv',
 '../wildfire-data/modis/2010/modis_2010_Nepal.csv',
 '../wildfire-data/modis/2019/modis_2019_Nepal.csv',
 '../wildfire-data/modis/2020/modis_2020_Nepal.csv',
 '../wildfire-data/modis/2018/modis_2018_Nepal.csv',
 '../wildfire-data/modis/2011/modis_2011_Nepal.csv',
 '../wildfire-data/modis/2016/modis_2016_Nepal.csv',
 '../wildfire-data/modis/2005/modis_2005_Nepal.csv',
 '../wildfire-data/modis/2002/modis_2002_Nepal.csv',
 '../wildfire-data/modis/2003/modis_2003_Nepal.csv',
 '../wildfire-data/modis/2004/modis_2004_Nepal.csv']

In [14]:
df_viirs = pd.read_csv('../wildfire-data/viirs-snpp/2020/viirs-snpp_2020_Nepal.csv')

In [15]:
df_viirs = pd.read_csv('../wildfire-data/viirs-snpp/2020/viirs-snpp_2020_Nepal.csv', low_memory=False)

In [16]:
df_viirs

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type
0,27.532799,83.409477,295.24,0.39,0.36,2020-01-04,2007,N,VIIRS,n,1,283.93,0.48,N,0
1,29.014025,82.741753,325.50,0.40,0.44,2020-01-11,710,N,VIIRS,l,1,296.50,3.10,D,0
2,28.972002,82.721237,329.05,0.40,0.44,2020-01-11,710,N,VIIRS,n,1,298.24,4.61,D,0
3,28.967470,82.850662,299.74,0.32,0.55,2020-01-11,1935,N,VIIRS,n,1,273.13,0.49,N,0
4,28.964066,82.850983,299.47,0.32,0.55,2020-01-11,1935,N,VIIRS,n,1,273.02,0.78,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9245,28.328114,84.929863,329.22,0.48,0.40,2020-12-31,2018,N,VIIRS,n,1,281.11,5.99,0,0
9246,28.331739,84.930809,324.43,0.48,0.40,2020-12-31,2018,N,VIIRS,n,1,279.79,2.50,0,0
9247,29.692017,81.372002,306.27,0.38,0.36,2020-12-31,2018,N,VIIRS,n,1,264.39,1.06,0,0
9248,28.328835,84.926025,327.65,0.48,0.40,2020-12-31,2018,N,VIIRS,n,1,283.64,9.41,0,0
9249,28.327314,84.927071,332.61,0.48,0.40,2020-12-31,2018,N,VIIRS,n,1,280.17,6.07,0,0

In [17]:
df_viirs['satellite'].unique()

array(['N'], dtype=object)

In [18]:
df_viirs['instrument'].unique()

array(['VIIRS'], dtype=object)

In [19]:
type(df_viirs.confidence[0])

str

In [20]:
isinstance(df_viirs.confidence[0], str)

True

In [21]:
df_viirs.confidence.unique()

array(['n', 'l', 'h'], dtype=object)

In [22]:
df_modis = pd.read_csv('../wildfire-data/modis/2020/modis_2020_Nepal.csv')

In [23]:
df_modis

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,28.5115,81.2492,300.0,1.5,1.2,2020-01-13,734,Aqua,MODIS,24,6.03,288.2,6.7,D,0
1,28.5604,82.7200,305.1,1.2,1.1,2020-01-13,734,Aqua,MODIS,45,6.03,294.2,8.2,D,0
2,26.6773,86.9825,317.9,1.1,1.1,2020-01-15,721,Aqua,MODIS,77,6.03,295.8,14.0,D,0
3,28.3409,84.4350,304.1,1.0,1.0,2020-01-20,740,Aqua,MODIS,58,6.03,282.9,8.3,D,0
4,28.6669,82.7348,307.1,1.5,1.2,2020-01-22,728,Aqua,MODIS,53,6.03,284.5,16.1,D,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1347,28.3312,84.4264,304.0,3.2,1.7,2020-12-31,817,Aqua,MODIS,57,6.03,292.6,34.2,D,0
1348,28.6429,82.7774,312.2,2.4,1.5,2020-12-31,817,Aqua,MODIS,31,6.03,300.9,32.2,D,0
1349,28.6385,82.7702,309.7,2.4,1.5,2020-12-31,817,Aqua,MODIS,49,6.03,299.0,25.0,D,0
1350,29.8585,81.2090,301.9,2.0,1.4,2020-12-31,817,Aqua,MODIS,36,6.03,283.6,21.1,D,0
1351,28.3304,84.9318,302.5,1.1,1.1,2020-12-31,2023,Aqua,MODIS,50,6.03,279.1,11.2,N,0

In [24]:
df_modis['satellite'].unique()

array(['Aqua', 'Terra'], dtype=object)

In [25]:
df_modis['instrument'].unique()

array(['MODIS'], dtype=object)

In [26]:
type(df_modis['confidence'][0])

numpy.int64

In [27]:
df_modis['confidence'].unique()

array([ 24,  45,  77,  58,  53,  72,  66,  50,  48,  37,  71,  41,  44,
        21,  26,  63,  51,  61,  43,  67,  59,  62,  73,  64,   0,  76,
        47,  54,  65,  69,  38,  29,  52,  60,  82,  32,  74,  42,  55,
        68,  19,  49,  57,  15,  35,  36,  85,  14,  78,  17,  81,  25,
        83,  84,  75,  94,  92,  93,  70,  80,  56,  40,  95,  86,  31,
        39,  22,  79,  12,  27,  90,  10, 100,  33,  30,  34,  89,  46,
        96,  87,  88,  18,  28,  91,   7,  23,  16,  97,  99,  20,  11,
        98,  13])

In [29]:
# Taken this idea from the H2O.ai wild fire competition github repo and changed it meet the local need
rows = []
fire_df = []
row_sum = 0
for f in tqdm(all_nepal_files):
    df = pd.read_csv(f, parse_dates=['acq_time'], low_memory=False) 
    csv_name = f.split('/')[-1]
    row = [
        f, csv_name, df.shape[0], df.shape[1], df.acq_date.min(), df.acq_date.max(),
        df.satellite.unique(), df.instrument.max(), df.version.max(),
        df.latitude.nunique(), df.longitude.nunique(),
        df.confidence.nunique(), df.satellite.nunique(), df.acq_date.nunique()
    ]
    if isinstance(df.confidence[0], str):
        df.confidence = df.confidence.replace({'l': 0, 'n': 50, 'h': 100})
    rows.append(row)
    row_sum = row_sum + df.shape[0]
    fire_df.append(df)
cols = [
    'path', 'csv', 'rows', 'cols', 'start', 'end',
    'satellite', 'instrument', 'version',
    'lats', 'lons', 'confs', 'sats', 'days'
]
filestats = pd.DataFrame(rows, columns=cols)
filestats.sort_values(by=['start', 'instrument'])
print("Total Rows: " + str(row_sum))

100%|█████████████████████████████████████████████████| 31/31 [00:00<00:00, 31.50it/s]

,path,csv,rows,cols,start,end,satellite,instrument,version,lats,lons,confs,sats,days
18,../wildfire-data/modis/2000/modis_2000_Nepal.csv,modis_2000_Nepal.csv,98,15,2000-11-01,2000-12-29,[Terra],MODIS,6.20,98,98,57,1,34
15,../wildfire-data/modis/2001/modis_2001_Nepal.csv,modis_2001_Nepal.csv,1238,15,2001-01-02,2001-12-29,[Terra],MODIS,6.20,1207,1222,91,1,139
28,../wildfire-data/modis/2002/modis_2002_Nepal.csv,modis_2002_Nepal.csv,487,15,2002-01-01,2002-12-30,"[Terra, Aqua]",MODIS,6.20,479,480,88,2,121
29,../wildfire-data/modis/2003/modis_2003_Nepal.csv,modis_2003_Nepal.csv,2202,15,2003-01-03,2003-12-31,"[Terra, Aqua]",MODIS,6.20,2091,2144,94,2,210
30,../wildfire-data/modis/2004/modis_2004_Nepal.csv,modis_2004_Nepal.csv,2846,15,2004-01-02,2004-12-30,"[Terra, Aqua]",MODIS,6.20,2682,2772,97,2,178
27,../wildfire-data/modis/2005/modis_2005_Nepal.csv,modis_2005_Nepal.csv,2676,15,2005-01-02,2005-12-31,"[Terra, Aqua]",MODIS,6.20,2540,2602,95,2,203
16,../wildfire-data/modis/2006/modis_2006_Nepal.csv,modis_2006_Nepal.csv,2349,15,2006-01-01,2006-12-31,"[Terra, Aqua]",MODIS,6.20,2218,2296,95,2,178
17,../wildfire-data/modis/2007/modis_2007_Nepal.csv,modis_2007_Nepal.csv,1353,15,2007-01-02,2007-12-31,"[Aqua, Terra]",MODIS,6.20,1306,1332,90,2,172
14,../wildfire-data/modis/2008/modis_2008_Nepal.csv,modis_2008_Nepal.csv,2990,15,2008-01-01,2008-12-31,"[Terra, Aqua]",MODIS,6.20,2792,2896,95,2,190
19,../wildfire-data/modis/2009/modis_2009_Nepal.csv,modis_2009_Nepal.csv,4704,15,2009-01-03,2009-12-31,"[Aqua, Terra]",MODIS,6.20,4287,4508,95,2,209
21,../wildfire-data/modis/2010/modis_2010_Nepal.csv,modis_2010_Nepal.csv,3242,15,2010-01-01,2010-12-31,"[Aqua, Terra]",MODIS,6.20,3027,3154,98,2,184
25,../wildfire-data/modis/2011/modis_2011_Nepal.csv,modis_2011_Nepal.csv,1908,15,2011-01-02,2011-12-31,"[Aqua, Terra]",MODIS,6.20,1821,1878,97,2,180
13,../wildfire-data/modis/2012/modis_2012_Nepal.csv,modis_2012_Nepal.csv,3581,15,2012-01-05,2012-12-31,"[Aqua, Terra]",MODIS,6.20,3333,3457,97,2,213
3,../wildfire-data/viirs-snpp/2012/viirs-snpp_20...,viirs-snpp_2012_Nepal.csv,31490,15,2012-01-20,2012-12-31,[N],VIIRS,1.00,30984,30739,3,1,226
10,../wildfire-data/modis/2013/modis_2013_Nepal.csv,modis_2013_Nepal.csv,2534,15,2013-01-01,2013-12-30,"[Terra, Aqua]",MODIS,6.20,2371,2470,97,2,174
0,../wildfire-data/viirs-snpp/2013/viirs-snpp_20...,viirs-snpp_2013_Nepal.csv,22665,15,2013-01-01,2013-12-31,[N],VIIRS,1.00,22429,22275,3,1,216
11,../wildfire-data/modis/2014/modis_2014_Nepal.csv,modis_2014_Nepal.csv,3443,15,2014-01-01,2014-12-31,"[Aqua, Terra]",MODIS,6.20,3212,3361,97,2,196
1,../wildfire-data/viirs-snpp/2014/viirs-snpp_20...,viirs-snpp_2014_Nepal.csv,35244,15,2014-01-01,2014-12-31,[N],VIIRS,1.00,34695,34490,3,1,228
2,../wildfire-data/viirs-snpp/2015/viirs-snpp_20...,viirs-snpp_2015_Nepal.csv,8669,15,2015-01-06,2015-12-31,[N],VIIRS,1.00,8629,8596,3,1,235
12,../wildfire-data/modis/2015/modis_2015_Nepal.csv,modis_2015_Nepal.csv,1083,15,2015-01-13,2015-12-31,"[Aqua, Terra]",MODIS,6.20,1047,1075,88,2,177
26,../wildfire-data/modis/2016/modis_2016_Nepal.csv,modis_2016_Nepal.csv,7767,15,2016-01-01,2016-12-31,"[Terra, Aqua]",MODIS,6.20,6655,7259,100,2,193
9,../wildfire-data/viirs-snpp/2016/viirs-snpp_20...,viirs-snpp_2016_Nepal.csv,62025,15,2016-01-01,2016-12-31,[N],VIIRS,1.00,60216,59437,3,1,234
4,../wildfire-data/viirs-snpp/2017/viirs-snpp_20...,viirs-snpp_2017_Nepal.csv,17721,15,2017-01-01,2017-12-31,[N],VIIRS,1.00,17579,17478,3,1,233
20,../wildfire-data/modis/2017/modis_2017_Nepal.csv,modis_2017_Nepal.csv,2218,15,2017-01-02,2017-12-31,"[Aqua, Terra]",MODIS,6.20,2106,2168,94,2,192
24,../wildfire-data/modis/2018/modis_2018_Nepal.csv,modis_2018_Nepal.csv,2990,15,2018-01-01,2018-12-31,"[Aqua, Terra]",MODIS,6.03,2789,2892,98,2,203
8,../wildfire-data/viirs-snpp/2018/viirs-snpp_20...,viirs-snpp_2018_Nepal.csv,21996,15,2018-01-01,2018-12-31,[N],VIIRS,1.00,21790,21615,3,1,243
22,../wildfire-data/modis/2019/modis_2019_Nepal.csv,modis_2019_Nepal.csv,3950,15,2019-01-01,2019-12-31,"[Aqua, Terra]",MODIS,6.03,3607,3773,99,2,186
5,../wildfire-data/viirs-snpp/2019/viirs-snpp_20...,viirs-snpp_2019_Nepal.csv,31299,15,2019-01-01,2019-12-31,[N],VIIRS,1.00,30800,30442,3,1,248
7,../wildfire-data/viirs-snpp/2020/viirs-snpp_20...,viirs-snpp_2020_Nepal.csv,9250,15,2020-01-04,2020-12-31,[N],VIIRS,1.00,9222,9173,3,1,223
23,../wildfire-data/modis/2020/modis_2020_Nepal.csv,modis_2020_Nepal.csv,1352,15,2020-01-13,2020-12-31,"[Aqua, Terra]",MODIS,6.03,1314,1329,93,2,173
6,../wildfire-data/viirs-snpp/2021/viirs-snpp_20...,viirs-snpp_2021_Nepal.csv,60358,15,2021-01-01,2021-12-31,[N],VIIRS,1.00,58649,57891,3,1,212

Total Rows: 355728

In [30]:
fire_df

[        latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0      26.669355  87.058891      351.25  0.39   0.36  2013-01-01     0720
 1      26.682751  86.993225      332.90  0.39   0.36  2013-01-01     0720
 2      26.682184  86.989326      346.14  0.39   0.36  2013-01-01     0720
 3      26.668783  87.054985      327.39  0.39   0.36  2013-01-01     0720
 4      26.659639  86.992599      329.09  0.39   0.36  2013-01-01     0720
 ...          ...        ...         ...   ...    ...         ...      ...
 22660  29.756262  81.242523      309.08  0.57   0.43  2013-12-30     0720
 22661  29.754240  81.240425      283.43  0.57   0.43  2013-12-30     0720
 22662  29.759514  81.246223      327.31  0.57   0.43  2013-12-30     0720
 22663  29.687540  81.122917      356.57  0.38   0.44  2013-12-30     0720
 22664  26.712027  87.000938      325.60  0.56   0.43  2013-12-31     0700

       satellite instrument  confidence  version  bright_ti5    frp daynight  \
 0             N      VIIRS          50        1      301.87   5.34        D
 1             N      VIIRS          50        1      301.59   4.50        D
 2             N      VIIRS          50        1      300.99   4.59        D
 3             N      VIIRS          50        1      297.92   2.54        D
 4             N      VIIRS           0        1      302.65   3.05        D
 ...         ...        ...         ...      ...         ...    ...      ...
 22660         N      VIIRS           0        1      314.78  56.85        D
 22661         N      VIIRS           0        1      291.71  62.01        D
 22662         N      VIIRS          50        1      279.88  62.01        D
 22663         N      VIIRS          50        1      285.62   9.14        D
 22664         N      VIIRS          50        1      296.75   3.11        D

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 22660     0
 22661     0
 22662     0
 22663     0
 22664     0

 [22665 rows x 15 columns],
         latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0      27.459518  87.429199      333.90  0.32   0.55  2014-01-01     0641
 1      26.638918  86.971214      328.86  0.36   0.57  2014-01-01     0641
 2      26.644104  86.969765      325.38  0.36   0.57  2014-01-01     0641
 3      26.644932  86.973343      326.44  0.36   0.57  2014-01-01     0641
 4      28.793547  82.492264      332.02  0.59   0.70  2014-01-01     0642
 ...          ...        ...         ...   ...    ...         ...      ...
 35239  29.755133  81.389313      338.31  0.49   0.40  2014-12-31     0803
 35240  29.660151  81.150246      330.92  0.47   0.40  2014-12-31     0803
 35241  29.405006  82.307671      331.03  0.53   0.42  2014-12-31     0803
 35242  29.405590  82.304901      329.04  0.53   0.42  2014-12-31     0803
 35243  26.789736  86.632156      296.61  0.42   0.45  2014-12-31     2028

       satellite instrument  confidence  version  bright_ti5    frp daynight  \
 0             N      VIIRS          50        1      287.46   3.11        D
 1             N      VIIRS          50        1      295.78   2.24        D
 2             N      VIIRS          50        1      294.46   2.24        D
 3             N      VIIRS          50        1      293.71   2.24        D
 4             N      VIIRS          50        1      281.27   9.27        D
 ...         ...        ...         ...      ...         ...    ...      ...
 35239         N      VIIRS          50        1      297.13  13.59        D
 35240         N      VIIRS          50        1      292.32   4.15        D
 35241         N      VIIRS          50        1      281.83   7.24        D
 35242         N      VIIRS          50        1      286.40   4.18        D
 35243         N      VIIRS          50        1      284.34   0.96        N

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 35239     0
 35240     0
 35241     0
 35242     0
 35243     0

 [35244 rows x 15 columns],
        latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0     26.790413  85.428757      329.71  0.50   0.41  2015-01-06     0749
 1     27.407551  83.783508      327.12  0.41   0.37  2015-01-07     0730
 2     26.618711  87.100845      326.01  0.39   0.36  2015-01-07     0730
 3     26.658651  87.761131      325.37  0.40   0.37  2015-01-07     0730
 4     26.766966  87.888443      332.91  0.41   0.37  2015-01-07     0730
 ...         ...        ...         ...   ...    ...         ...      ...
 8664  29.745024  81.344849      302.89  0.40   0.60  2015-12-31     1938
 8665  29.827112  82.107925      300.88  0.36   0.57  2015-12-31     1938
 8666  28.969362  82.633888      295.15  0.75   0.77  2015-12-31     2118
 8667  28.944122  82.748100      305.26  0.76   0.77  2015-12-31     2118
 8668  29.017040  81.386215      298.24  0.63   0.72  2015-12-31     2118

      satellite instrument  confidence  version  bright_ti5   frp daynight  \
 0            N      VIIRS          50        1      289.58  3.42        D
 1            N      VIIRS          50        1      292.86  1.82        D
 2            N      VIIRS          50        1      292.66  1.25        D
 3            N      VIIRS          50        1      294.34  1.88        D
 4            N      VIIRS          50        1      293.81  4.42        D
 ...        ...        ...         ...      ...         ...   ...      ...
 8664         N      VIIRS          50        1      272.89  1.80        N
 8665         N      VIIRS          50        1      275.24  1.02        N
 8666         N      VIIRS          50        1      276.94  2.39        N
 8667         N      VIIRS          50        1      273.11  3.60        N
 8668         N      VIIRS          50        1      267.57  1.44        N

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 8664     0
 8665     0
 8666     0
 8667     0
 8668     0

 [8669 rows x 15 columns],
         latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0      26.650742  86.959084      333.02  0.42   0.38  2012-01-20     0728
 1      26.621929  86.981117      325.71  0.42   0.38  2012-01-20     0728
 2      26.625381  86.980537      340.33  0.42   0.38  2012-01-20     0728
 3      26.648424  86.968094      330.45  0.42   0.38  2012-01-20     0728
 4      26.647289  86.959663      325.98  0.42   0.38  2012-01-20     0728
 ...          ...        ...         ...   ...    ...         ...      ...
 31485  29.613806  82.366623      327.31  0.41   0.37  2012-12-31     2005
 31486  29.746492  81.318138      302.59  0.45   0.39  2012-12-31     2005
 31487  29.743042  81.316864      310.59  0.45   0.39  2012-12-31     2005
 31488  29.155554  81.957817      304.57  0.42   0.38  2012-12-31     2005
 31489  28.479004  84.906372      315.84  0.39   0.36  2012-12-31     2005

       satellite instrument  confidence  version  bright_ti5   frp daynight  \
 0             N      VIIRS          50        1      295.28  4.08        D
 1             N      VIIRS          50        1      295.49  7.35        D
 2             N      VIIRS          50        1      296.81  7.35        D
 3             N      VIIRS          50        1      296.76  2.07        D
 4             N      VIIRS          50        1      295.20  4.08        D
 ...         ...        ...         ...      ...         ...   ...      ...
 31485         N      VIIRS          50        1      266.83  2.49        N
 31486         N      VIIRS          50        1      276.17  1.27        N
 31487         N      VIIRS          50        1      276.53  1.27        N
 31488         N      VIIRS          50        1      274.92  0.89        N
 31489         N      VIIRS          50        1      273.94  2.07        N

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 31485     0
 31486     0
 31487     0
 31488     0
 31489     0

 [31490 rows x 15 columns],
         latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0      26.742233  87.885094      327.06  0.46   0.39  2017-01-01     0729
 1      26.596781  87.177055      326.89  0.43   0.38  2017-01-01     0729
 2      28.731194  80.302666      342.03  0.46   0.39  2017-01-01     0730
 3      28.629143  80.463600      330.35  0.45   0.39  2017-01-01     0730
 4      28.734762  80.301849      340.24  0.46   0.39  2017-01-01     0730
 ...          ...        ...         ...   ...    ...         ...      ...
 17716  28.581041  80.464516      329.63  0.76   0.77  2017-12-31     0845
 17717  28.579334  80.464767      329.56  0.76   0.77  2017-12-31     0845
 17718  27.059858  87.148735      307.07  0.41   0.45  2017-12-31     1930
 17719  28.421991  83.863434      317.25  0.34   0.56  2017-12-31     1930
 17720  28.425499  83.864883      308.01  0.34   0.56  2017-12-31     1930

       satellite instrument  confidence  version  bright_ti5    frp daynight  \
 0             N      VIIRS          50        1      288.97   2.06        D
 1             N      VIIRS          50        1      298.90   2.09        D
 2             N      VIIRS          50        1      296.53  14.77        D
 3             N      VIIRS          50        1      294.79   2.33        D
 4             N      VIIRS          50        1      292.98   9.45        D
 ...         ...        ...         ...      ...         ...    ...      ...
 17716         N      VIIRS          50        1      291.36  11.77        D
 17717         N      VIIRS          50        1      291.81   7.67        D
 17718         N      VIIRS          50        1      283.40   0.79        N
 17719         N      VIIRS          50        1      269.37   1.55        N
 17720         N      VIIRS          50        1      268.72   1.56        N

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 17716     0
 17717     0
 17718     0
 17719     0
 17720     0

 [17721 rows x 15 columns],
         latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0      27.758892  87.351112      326.39  0.43   0.46  2019-01-01     0742
 1      28.225370  84.963837      326.32  0.49   0.40  2019-01-01     0742
 2      28.437172  84.877861      330.25  0.49   0.40  2019-01-01     0742
 3      28.511000  84.879654      333.12  0.49   0.40  2019-01-01     0742
 4      28.440168  84.871658      344.16  0.49   0.40  2019-01-01     0742
 ...          ...        ...         ...   ...    ...         ...      ...
 31294  26.519121  87.820175      332.10  0.38   0.36  2019-12-31     0716
 31295  27.604916  85.312752      326.18  0.41   0.37  2019-12-31     0716
 31296  27.470068  85.137650      329.73  0.42   0.38  2019-12-31     0716
 31297  29.051338  82.834587      330.28  0.49   0.40  2019-12-31     0717
 31298  29.808924  80.934929      332.83  0.40   0.44  2019-12-31     0717

       satellite instrument  confidence  version  bright_ti5   frp daynight  \
 0             N      VIIRS          50        1      284.10  2.57        D
 1             N      VIIRS          50        1      299.28  5.50        D
 2             N      VIIRS          50        1      297.42  7.26        D
 3             N      VIIRS          50        1      290.33  5.05        D
 4             N      VIIRS          50        1      300.56  7.26        D
 ...         ...        ...         ...      ...         ...   ...      ...
 31294         N      VIIRS          50        1      299.75  5.25        D
 31295         N      VIIRS          50        1      282.98  1.84        D
 31296         N      VIIRS          50        1      291.87  4.81        D
 31297         N      VIIRS          50        1      291.11  5.00        D
 31298         N      VIIRS          50        1      290.24  5.40        D

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 31294     0
 31295     0
 31296     0
 31297     0
 31298     0

 [31299 rows x 15 columns],
         latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0      26.901299  86.139061      336.13  0.45   0.39  2021-01-01     0730
 1      26.867010  85.364693      331.73  0.42   0.38  2021-01-01     0730
 2      27.094315  85.044273      326.36  0.42   0.37  2021-01-01     0730
 3      27.454939  84.928452      333.62  0.41   0.37  2021-01-01     0730
 4      28.313885  84.822487      345.26  0.42   0.37  2021-01-01     0730
 ...          ...        ...         ...   ...    ...         ...      ...
 60353  27.125383  84.859642      332.21  0.39   0.36  2021-12-25     0724
 60354  27.128704  84.858986      331.20  0.39   0.36  2021-12-25     0724
 60355  28.698627  80.359848      330.97  0.54   0.42  2021-12-25     0724
 60356  28.820669  80.171555      332.00  0.55   0.43  2021-12-25     0724
 60357  29.633783  81.807281      329.38  0.43   0.46  2021-12-31     0712

       satellite instrument  confidence  version  bright_ti5    frp daynight  \
 0             N      VIIRS          50        1      301.87   5.08        D
 1             N      VIIRS          50        1      298.82   2.51        D
 2             N      VIIRS          50        1      297.62   1.48        D
 3             N      VIIRS          50        1      299.03   5.78        D
 4             N      VIIRS          50        1      299.64  11.09        D
 ...         ...        ...         ...      ...         ...    ...      ...
 60353         N      VIIRS          50        1      296.39   2.05        D
 60354         N      VIIRS          50        1      293.93   2.05        D
 60355         N      VIIRS          50        1      294.96   8.72        D
 60356         N      VIIRS          50        1      296.71   3.87        D
 60357         N      VIIRS          50        1      294.68   3.30        D

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 60353     0
 60354     0
 60355     0
 60356     0
 60357     0

 [60358 rows x 15 columns],
        latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0     27.532799  83.409477      295.24  0.39   0.36  2020-01-04     2007
 1     29.014025  82.741753      325.50  0.40   0.44  2020-01-11     0710
 2     28.972002  82.721237      329.05  0.40   0.44  2020-01-11     0710
 3     28.967470  82.850662      299.74  0.32   0.55  2020-01-11     1935
 4     28.964066  82.850983      299.47  0.32   0.55  2020-01-11     1935
 ...         ...        ...         ...   ...    ...         ...      ...
 9245  28.328114  84.929863      329.22  0.48   0.40  2020-12-31     2018
 9246  28.331739  84.930809      324.43  0.48   0.40  2020-12-31     2018
 9247  29.692017  81.372002      306.27  0.38   0.36  2020-12-31     2018
 9248  28.328835  84.926025      327.65  0.48   0.40  2020-12-31     2018
 9249  28.327314  84.927071      332.61  0.48   0.40  2020-12-31     2018

      satellite instrument  confidence  version  bright_ti5   frp daynight  \
 0            N      VIIRS          50        1      283.93  0.48        N
 1            N      VIIRS           0        1      296.50  3.10        D
 2            N      VIIRS          50        1      298.24  4.61        D
 3            N      VIIRS          50        1      273.13  0.49        N
 4            N      VIIRS          50        1      273.02  0.78        N
 ...        ...        ...         ...      ...         ...   ...      ...
 9245         N      VIIRS          50        1      281.11  5.99        0
 9246         N      VIIRS          50        1      279.79  2.50        0
 9247         N      VIIRS          50        1      264.39  1.06        0
 9248         N      VIIRS          50        1      283.64  9.41        0
 9249         N      VIIRS          50        1      280.17  6.07        0

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 9245     0
 9246     0
 9247     0
 9248     0
 9249     0

 [9250 rows x 15 columns],
         latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0      28.597708  83.409172      367.00  0.60   0.71  2018-01-01     0826
 1      28.599108  83.409851      349.68  0.60   0.71  2018-01-01     0826
 2      28.598953  83.407013      367.00  0.60   0.71  2018-01-01     0826
 3      28.597561  83.406303      354.47  0.60   0.71  2018-01-01     0826
 4      28.592434  83.408409      352.83  0.60   0.71  2018-01-01     0826
 ...          ...        ...         ...   ...    ...         ...      ...
 21991  29.673677  81.255600      367.00  0.39   0.44  2018-12-31     0802
 21992  28.944426  82.277428      327.78  0.43   0.46  2018-12-31     0802
 21993  28.820290  80.152489      350.97  0.50   0.41  2018-12-31     0802
 21994  29.964392  80.661400      295.94  0.39   0.36  2018-12-31     2026
 21995  29.973719  80.667221      298.57  0.39   0.36  2018-12-31     2026

       satellite instrument  confidence  version  bright_ti5    frp daynight  \
 0             N      VIIRS           0        1      289.67  25.02        D
 1             N      VIIRS          50        1      283.67  26.76        D
 2             N      VIIRS           0        1      283.03  22.98        D
 3             N      VIIRS          50        1      284.27  25.02        D
 4             N      VIIRS          50        1      288.61  12.07        D
 ...         ...        ...         ...      ...         ...    ...      ...
 21991         N      VIIRS         100        1      300.13  11.81        D
 21992         N      VIIRS          50        1      296.21   3.15        D
 21993         N      VIIRS          50        1      307.96  23.37        D
 21994         N      VIIRS          50        1      277.86   0.32        N
 21995         N      VIIRS          50        1      276.02   0.58        N

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 21991     0
 21992     0
 21993     0
 21994     0
 21995     0

 [21996 rows x 15 columns],
         latitude  longitude  bright_ti4  scan  track    acq_date acq_time  \
 0      27.305805  87.467239      339.65  0.43   0.46  2016-01-01     0654
 1      28.299379  84.649651      325.03  0.60   0.53  2016-01-01     0654
 2      29.081198  82.880005      349.45  0.36   0.58  2016-01-01     0654
 3      28.812500  80.129784      327.45  0.53   0.67  2016-01-01     0654
 4      29.081699  82.882118      367.00  0.36   0.58  2016-01-01     0654
 ...          ...        ...         ...   ...    ...         ...      ...
 62020  28.782421  80.211029      329.85  0.39   0.36  2016-12-31     0749
 62021  28.786793  80.193779      344.48  0.39   0.36  2016-12-31     0749
 62022  28.810978  80.242828      334.70  0.39   0.36  2016-12-31     0749
 62023  29.865654  80.603920      339.93  0.40   0.37  2016-12-31     0749
 62024  28.689222  80.458389      325.11  0.40   0.37  2016-12-31     0749

       satellite instrument  confidence  version  bright_ti5    frp daynight  \
 0             N      VIIRS          50        1      285.16   4.65        D
 1             N      VIIRS          50        1      285.18   7.49        D
 2             N      VIIRS          50        1      267.45  14.14        D
 3             N      VIIRS          50        1      292.56   2.95        D
 4             N      VIIRS           0        1      272.69  30.00        D
 ...         ...        ...         ...      ...         ...    ...      ...
 62020         N      VIIRS          50        1      290.34   5.41        D
 62021         N      VIIRS          50        1      298.59  11.92        D
 62022         N      VIIRS          50        1      295.74   3.37        D
 62023         N      VIIRS          50        1      299.22   6.12        D
 62024         N      VIIRS          50        1      294.44   1.45        D

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 62020     0
 62021     0
 62022     0

In [31]:
nepal_fire_df = pd.concat(fire_df)
nepal_fire_df.shape

(355728, 17)

In [33]:
nepal_fire_df.sample(10)

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type,brightness,bright_t31
15827,27.306908,86.118263,333.89,0.60,0.53,2019-05-06,1923,N,VIIRS,50,1.0,290.46,4.11,N,0,NaN,NaN
4802,29.004330,81.190430,300.61,0.38,0.36,2021-03-05,2018,N,VIIRS,50,1.0,286.68,0.75,N,0,NaN,NaN
12527,27.688040,83.658524,297.81,0.44,0.46,2021-03-23,1942,N,VIIRS,50,1.0,285.25,0.38,N,0,NaN,NaN
289,28.475359,84.944557,342.30,0.57,0.43,2015-02-09,0711,N,VIIRS,50,1.0,299.71,7.60,D,0,NaN,NaN
38311,28.239475,81.786629,339.92,0.47,0.48,2016-04-15,1949,N,VIIRS,50,1.0,300.59,2.73,N,0,NaN,NaN
20193,27.586031,83.596649,340.89,0.39,0.36,2016-04-09,0736,N,VIIRS,0,1.0,315.82,1.80,D,0,NaN,NaN
15062,27.844988,82.291260,314.80,0.54,0.50,2019-05-05,1942,N,VIIRS,50,1.0,296.49,4.11,N,0,NaN,NaN
7681,28.398400,82.945900,NaN,1.20,1.10,2016-12-20,0505,Terra,MODIS,70,6.2,NaN,12.40,D,0,310.2,290.7
2703,27.878843,84.629196,301.39,0.39,0.44,2020-04-05,1942,N,VIIRS,50,1.0,288.98,0.91,N,0,NaN,NaN
363,28.610355,83.693398,313.19,0.68,0.74,2016-01-12,1912,N,VIIRS,50,1.0,265.64,3.62,N,0,NaN,NaN

In [34]:
nepal_fire_df = nepal_fire_df.sort_values(by=['acq_date', 'acq_time'])

In [35]:
nepal_fire_df

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type,brightness,bright_t31
0,27.592100,87.538500,NaN,1.10,1.10,2000-11-01,0500,Terra,MODIS,55,6.2,NaN,6.20,D,0,306.2,292.1
1,29.100600,81.917000,NaN,1.30,1.10,2000-11-06,0518,Terra,MODIS,87,6.2,NaN,43.00,D,0,330.6,293.7
2,30.088100,81.335800,NaN,1.80,1.30,2000-11-07,0601,Terra,MODIS,58,6.2,NaN,21.10,D,0,308.7,291.2
3,30.084100,81.357000,NaN,1.90,1.30,2000-11-07,0601,Terra,MODIS,37,6.2,NaN,17.10,D,0,306.0,287.4
4,30.106000,81.964700,NaN,2.10,1.40,2000-11-08,0506,Terra,MODIS,64,6.2,NaN,41.60,D,0,315.0,282.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60353,27.125383,84.859642,332.21,0.39,0.36,2021-12-25,0724,N,VIIRS,50,1.0,296.39,2.05,D,0,NaN,NaN
60354,27.128704,84.858986,331.20,0.39,0.36,2021-12-25,0724,N,VIIRS,50,1.0,293.93,2.05,D,0,NaN,NaN
60355,28.698627,80.359848,330.97,0.54,0.42,2021-12-25,0724,N,VIIRS,50,1.0,294.96,8.72,D,0,NaN,NaN
60356,28.820669,80.171555,332.00,0.55,0.43,2021-12-25,0724,N,VIIRS,50,1.0,296.71,3.87,D,0,NaN,NaN
60357,29.633783,81.807281,329.38,0.43,0.46,2021-12-31,0712,N,VIIRS,50,1.0,294.68,3.30,D,0,NaN,NaN

In [36]:
nepal_fire_df['confidence'].nunique()

101

In [37]:
nepal_fire_df['confidence'].unique()

array([ 55,  87,  58,  37,  64,  24,  63,  38,  27,   0,  14,  80,  51,
        35,  17,  47,  43,  72,  71,  70,  46,  48,  34,  53,  88,  85,
        67,  82,  30,  68,  79,  21,  69,  45,  95, 100,  25,  56,  36,
        78,  32,  83,  52,  77,  62,  92,  75,  60,  76,  40,  15,  90,
        59,  39,  74,  89,  94,  57,  33,  49,  12,  29,  41,  54,  20,
        23,  61,  96,  65,  86,  97,  42,  84,  73,  99,  66,  31,  50,
        16,  28,  44,  81,  19,   6,  11,  93,  26,  18,  22,  91,  98,
         9,   7,  13,   8,  10,   5,   3,   4,   2,   1])

# Brightness #
- brightness: Channel 21/22 brightness temperature of the fire pixel measured in Kelvin.

In [38]:
nepal_fire_df['brightness'].describe()

count    55011.000000
mean       319.632477
std         11.755701
min        300.000000
25%        310.800000
50%        319.800000
75%        326.000000
max        477.200000
Name: brightness, dtype: float64

## Satellite ##

In [39]:
nepal_fire_df['satellite'].unique()

array(['Terra', 'Aqua', 'N'], dtype=object)

In [40]:
nepal_fire_df['instrument'].unique()

array(['MODIS', 'VIIRS'], dtype=object)

## bright_t31 ##
- Channel 31 brightness temperature of the fire pixel measured in Kelvin.

In [41]:
nepal_fire_df['bright_t31'].describe()

count    55011.000000
mean       300.439956
std          8.388547
min        265.200000
25%        294.000000
50%        301.500000
75%        306.900000
max        328.000000
Name: bright_t31, dtype: float64

In [42]:
nepal_fire_df['bright_t31'].unique()

array([292.1, 293.7, 291.2, 287.4, 282.6, 293.4, 289.1, 293.6, 284.1,
       284.5, 287. , 288.6, 288.8, 287.2, 285.3, 286.8, 294.8, 294. ,
       292.7, 280.4, 289.3, 296.8, 281. , 292.4, 292.3, 288.7, 295.7,
       294.4, 295.6, 288.9, 283. , 286.3, 290.7, 282.8, 282.5, 289.7,
       291. , 293.5, 293.2, 291.9, 296.2, 291.5, 295.4, 296.5, 295.2,
       292.8, 298.2, 287.5, 290.4, 288.2, 297.6, 291.4, 297. , 296. ,
       286.2, 293.8, 296.4, 290.1, 289.8, 290.2, 290.9, 297.4, 293. ,
       291.7, 289.6, 291.8, 294.7, 298.5, 285.9, 297.7, 291.6, 290.5,
       289.4, 287.8, 284. , 286.9, 294.5, 281.4, 287.1, 282.1, 283.5,
       282.2, 293.1, 279.3, 278.2, 284.8, 292. , 288.3, 288.5, 286. ,
       287.7, 287.6, 294.6, 283.1, 285. , 292.9, 285.8, 281.1, 291.1,
       285.7, 285.6, 291.3, 286.7, 273. , 293.3, 302.6, 298.9, 277.8,
       286.4, 297.1, 292.5, 289.5, 302.4, 296.1, 294.3, 281.5, 271. ,
       293.9, 290.8, 292.2, 286.6, 301.8, 298.3, 294.1, 275.9, 295.9,
       290.6, 301.7, 298.7, 289.2, 302.2, 303.1, 295.1, 294.9, 300. ,
       300.2, 296.3, 296.9, 295.3, 296.6, 297.2, 299.3, 299.1, 299.5,
       302.1, 304.7, 301.6, 302.7, 301.5, 309.1, 297.8, 298.6, 305.6,
       305.5, 308.1, 311.2, 315.1, 307. , 305.2, 299.8, 300.6, 300.7,
       300.5, 289. , 301.9, 300.9, 303.2, 303.7, 285.2, 299.6, 300.4,
       303.6, 305.1, 304.8, 307.7, 307.8, 303.3, 304.3, 289.9, 301.3,
       299.7, 306. , 305.4, 303.8, 290.3, 302. , 303. , 304.5, 307.3,
       304.6, 280.1, 297.9, 301.4, 300.3, 301.2, 305.8, 302.9, 305. ,
       300.8, 302.8, 305.7, 304.1, 303.5, 304.2, 302.5, 304.9, 299. ,
       300.1, 299.2, 301.1, 307.2, 311.3, 311. , 308.5, 310.4, 311.6,
       309.5, 307.4, 304.4, 299.9, 306.8, 306.7, 307.1, 306.6, 305.9,
       301. , 306.1, 303.9, 292.6, 290. , 294.2, 310.5, 308. , 308.7,
       306.9, 304. , 298.1, 310.2, 311.5, 307.6, 306.5, 311.4, 308.4,
       307.5, 309.7, 310.8, 295.8, 285.5, 282.4, 302.3, 305.3, 306.4,
       307.9, 309. , 311.9, 306.3, 308.2, 310.1, 308.3, 309.2, 309.3,
       313.3, 312.4, 310.6, 308.6, 309.6, 309.4, 310. , 313.6, 312. ,
       309.9, 312.2, 295.5, 303.4, 296.7, 297.3, 297.5, 295. , 298.8,
       288.4, 298.4, 306.2, 311.1, 310.7, 308.9, 312.5, 312.1, 316.1,
       315. , 314. , 315.8, 313.5, 310.9, 311.7, 313.9, 309.8, 283.7,
       272.6, 268.7, 286.1, 269. , 284.9, 281.2, 274.1, 283.4, 279.8,
       278.5, 281.8, 270.4, 279.4, 277.3, 276.9, 283.2, 275.4, 284.3,
       281.7, 277. , 278.8, 282.9, 287.3, 276.5, 279.7, 280.8, 287.9,
       274.6, 285.4, 283.6, 284.7, 286.5, 298. , 299.4, 275.2, 311.8,
       288.1, 273.5, 270.7, 271.7, 284.4, 277.5, 280.6, 281.6, 284.2,
       281.3, 284.6, 280.5, 277.6, 283.8, 282. , 276.6, 277.7, 276.8,
       273.9, 282.7, 288. , 313.2, 281.9, 277.9, 313.4, 312.3, 308.8,
       312.6, 312.9, 280. , 315.6, 314.4, 314.9, 312.7, 314.3, 313.8,
       310.3, 318.9, 315.2, 317.4, 312.8, 314.7, 314.6, 314.8, 313.1,
       317.3, 314.1, 314.2, 320.3, 319.1, 314.5, 315.4, 279. , 313. ,
       313.7, 316. , 316.2, 318.1, 317.6, 316.5, 316.3, 317.2, 266.5,
       279.1, 285.1, 280.2, 278.1, 282.3, 279.6, 279.5, 273.3, 275.8,
       277.4, 271.6, 280.3, 283.3, 274.2, 275.7, 272.7, 278.9, 279.2,
       268.8, 267.8, 266.1, 275.6, 319.4, 315.9, 316.7, 315.7, 316.4,
       315.5, 269.5, 278.3, 283.9, 275.3, 279.9, 280.9, 317.1, 317.8,
       316.8, 316.9, 276.2, 277.1, 276.7, 318.2, 318.4, 320.7, 318.5,
       319. , 315.3, 318.6, 317. , 319.9, 272.9, 271.1, 276. , 276.3,
       280.7, 273.6, 268.4, 271.2, 272.1, 269.1, 276.4, 276.1, 274.3,
       272.2, 271.5, 273.1, 318. , 319.8, 317.9, 318.8, 275.5, 278.6,
       278. , 270.5, 271.4, 274.4, 270.2, 274.5, 271.9, 277.2, 318.7,
       316.6, 317.5, 278.7, 275.1, 273.4, 270.9, 273.7, 274.8, 272.5,
       278.4, 272.3, 265.2, 270.8, 274.9, 268.2, 269.9, 268.3, 317.7,
       319.3, 318.3, 321.3, 320.8, 321.4, 319.5, 319.2, 321.1, 319.6,
       322.9, 324.7, 324.4, 272.4, 270. , 275. ,   nan, 272.8, 320.4,
       321.5, 269.7, 269.6, 320.2, 323.3, 320. , 321.2, 273.8, 274. ,
       269.8, 271.8, 266.8, 268.1, 266.2, 267.9, 328. , 320.6, 321.7,
       321.6, 319.7, 267.7, 266.9, 273.2, 268.9, 272. , 320.5, 267.1,
       265.9, 270.3, 265.4, 266.4])

## frp ##
- Fire Radiative Power depicts the pixel-integrated fire radiative power in MW (megawatts).

In [43]:
nepal_fire_df['frp'].describe()

count    355728.000000
mean          6.503891
std          15.557042
min           0.000000
25%           1.380000
50%           3.030000
75%           6.730000
max        2321.200000
Name: frp, dtype: float64

## type ##
- Inferred hot spot type
  - 0 = presumed vegetation fire
  - 1 = active volcano
  - 2 = other static land source
  - 3 = offshore

In [44]:
nepal_fire_df['type'].unique()

array([0, 3, 2])

## Confidence ##
- This value is based on a collection of intermediate algorithm quantities used in the detection process. 
- It is intended to help users gauge the quality of individual hotspot/fire pixels. 
- Confidence estimates range between 0 and 100% and are assigned one of the three fire classes
  - low-confidence fire
  - nominal-confidence fire
  - high-confidence fire).

In [45]:
nepal_fire_df['confidence'].unique()

array([ 55,  87,  58,  37,  64,  24,  63,  38,  27,   0,  14,  80,  51,
        35,  17,  47,  43,  72,  71,  70,  46,  48,  34,  53,  88,  85,
        67,  82,  30,  68,  79,  21,  69,  45,  95, 100,  25,  56,  36,
        78,  32,  83,  52,  77,  62,  92,  75,  60,  76,  40,  15,  90,
        59,  39,  74,  89,  94,  57,  33,  49,  12,  29,  41,  54,  20,
        23,  61,  96,  65,  86,  97,  42,  84,  73,  99,  66,  31,  50,
        16,  28,  44,  81,  19,   6,  11,  93,  26,  18,  22,  91,  98,
         9,   7,  13,   8,  10,   5,   3,   4,   2,   1])

In [ ]:
nepal_fire_df.columns

## Extracting few main feautures from the dataset ##

In [46]:
daily_fires_df = nepal_fire_df.groupby(
            ['latitude', 'longitude', 'acq_date', 'satellite', 'instrument', 'frp', 'type', 'bright_t31']).confidence.max().reset_index()

In [47]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence
0,26.3775,87.3273,2020-11-07,Aqua,MODIS,7.0,0,301.3,57
1,26.4124,87.2421,2019-02-04,Aqua,MODIS,6.7,0,297.4,60
2,26.4171,87.5787,2018-03-06,Terra,MODIS,19.3,0,303.1,80
3,26.4265,87.5735,2013-02-26,Aqua,MODIS,4.8,0,302.9,43
4,26.4285,87.2503,2015-03-21,Terra,MODIS,7.0,0,303.1,62
...,...,...,...,...,...,...,...,...,...
55006,30.2113,81.9902,2012-06-29,Aqua,MODIS,10.3,0,306.9,56
55007,30.2321,82.0426,2002-10-22,Aqua,MODIS,13.1,0,286.1,41
55008,30.2455,81.6329,2003-12-14,Aqua,MODIS,8.2,0,289.2,37
55009,30.2470,81.6431,2003-12-14,Aqua,MODIS,10.0,0,286.7,58
55010,30.2669,81.4897,2016-12-10,Aqua,MODIS,6.7,0,283.3,28

In [48]:
daily_fires_df = daily_fires_df[daily_fires_df.confidence >= 50]

In [49]:
daily_fires_df['confidence'].unique()

array([ 57,  60,  80,  62,  81,  64,  63,  78,  56,  95,  73,  69,  58,
        86,  66,  77,  51,  67,  50,  52,  82,  59,  97,  53,  55,  74,
        75,  71,  72,  54,  70,  87,  76,  99,  85,  61,  68,  65,  88,
       100,  84,  79,  83,  92,  89,  94,  90,  91,  98,  96,  93])

In [50]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence
0,26.3775,87.3273,2020-11-07,Aqua,MODIS,7.0,0,301.3,57
1,26.4124,87.2421,2019-02-04,Aqua,MODIS,6.7,0,297.4,60
2,26.4171,87.5787,2018-03-06,Terra,MODIS,19.3,0,303.1,80
4,26.4285,87.2503,2015-03-21,Terra,MODIS,7.0,0,303.1,62
5,26.4309,87.2452,2011-04-24,Terra,MODIS,43.0,0,298.4,81
...,...,...,...,...,...,...,...,...,...
55003,30.1793,80.8618,2016-12-16,Terra,MODIS,30.7,0,288.9,86
55004,30.1846,80.8731,2016-12-15,Aqua,MODIS,31.6,0,272.1,56
55005,30.1850,82.0371,2011-10-18,Terra,MODIS,26.2,0,287.2,85
55006,30.2113,81.9902,2012-06-29,Aqua,MODIS,10.3,0,306.9,56
55009,30.2470,81.6431,2003-12-14,Aqua,MODIS,10.0,0,286.7,58

In [51]:
daily_fires_df['acq_date'].min()

'2000-11-01'

In [52]:
daily_fires_df['acq_date'].max()

'2020-12-31'

In [53]:
daily_fires_df.describe()

,latitude,longitude,frp,type,bright_t31,confidence
count,40238.000000,40238.000000,40238.000000,40238.000000,40238.000000,40238.000000
mean,28.130197,83.232009,23.558335,0.000249,301.185633,69.580272
std,0.752369,2.100635,38.045217,0.022293,8.231211,12.217158
min,26.377500,80.031500,0.000000,0.000000,265.200000,50.000000
25%,27.534400,81.495525,9.500000,0.000000,294.900000,60.000000
50%,28.114000,82.731800,14.300000,0.000000,302.100000,69.000000
75%,28.722900,84.813875,24.500000,0.000000,307.500000,78.000000
max,30.247000,88.146000,2321.200000,2.000000,328.000000,100.000000

In [54]:
daily_fires_df['acq_date'] = pd.to_datetime(daily_fires_df['acq_date'])

/var/folders/j9/zkczhkln1w95vm9cj3p_qzhr0000gp/T/ipykernel_30675/1911553507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_fires_df['acq_date'] = pd.to_datetime(daily_fires_df['acq_date'])

In [55]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence
0,26.3775,87.3273,2020-11-07,Aqua,MODIS,7.0,0,301.3,57
1,26.4124,87.2421,2019-02-04,Aqua,MODIS,6.7,0,297.4,60
2,26.4171,87.5787,2018-03-06,Terra,MODIS,19.3,0,303.1,80
4,26.4285,87.2503,2015-03-21,Terra,MODIS,7.0,0,303.1,62
5,26.4309,87.2452,2011-04-24,Terra,MODIS,43.0,0,298.4,81
...,...,...,...,...,...,...,...,...,...
55003,30.1793,80.8618,2016-12-16,Terra,MODIS,30.7,0,288.9,86
55004,30.1846,80.8731,2016-12-15,Aqua,MODIS,31.6,0,272.1,56
55005,30.1850,82.0371,2011-10-18,Terra,MODIS,26.2,0,287.2,85
55006,30.2113,81.9902,2012-06-29,Aqua,MODIS,10.3,0,306.9,56
55009,30.2470,81.6431,2003-12-14,Aqua,MODIS,10.0,0,286.7,58

In [56]:
daily_fires_df['year'] = daily_fires_df.acq_date.dt.year

/var/folders/j9/zkczhkln1w95vm9cj3p_qzhr0000gp/T/ipykernel_30675/2902059493.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_fires_df['year'] = daily_fires_df.acq_date.dt.year

In [57]:
daily_fires_df['month'] = daily_fires_df.acq_date.dt.month

/var/folders/j9/zkczhkln1w95vm9cj3p_qzhr0000gp/T/ipykernel_30675/1262889700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_fires_df['month'] = daily_fires_df.acq_date.dt.month

In [58]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence,year,month
0,26.3775,87.3273,2020-11-07,Aqua,MODIS,7.0,0,301.3,57,2020,11
1,26.4124,87.2421,2019-02-04,Aqua,MODIS,6.7,0,297.4,60,2019,2
2,26.4171,87.5787,2018-03-06,Terra,MODIS,19.3,0,303.1,80,2018,3
4,26.4285,87.2503,2015-03-21,Terra,MODIS,7.0,0,303.1,62,2015,3
5,26.4309,87.2452,2011-04-24,Terra,MODIS,43.0,0,298.4,81,2011,4
...,...,...,...,...,...,...,...,...,...,...,...
55003,30.1793,80.8618,2016-12-16,Terra,MODIS,30.7,0,288.9,86,2016,12
55004,30.1846,80.8731,2016-12-15,Aqua,MODIS,31.6,0,272.1,56,2016,12
55005,30.1850,82.0371,2011-10-18,Terra,MODIS,26.2,0,287.2,85,2011,10
55006,30.2113,81.9902,2012-06-29,Aqua,MODIS,10.3,0,306.9,56,2012,6
55009,30.2470,81.6431,2003-12-14,Aqua,MODIS,10.0,0,286.7,58,2003,12

In [59]:
daily_fires_df['acq_date'].min()

Timestamp('2000-11-01 00:00:00')

In [60]:
daily_fires_df['acq_date'].max()

Timestamp('2020-12-31 00:00:00')

In [61]:
daily_fires_df.to_csv('nepal_daily_fire_2000_2020.csv', index=False)
#ca_daily_fire.to_csv('ca_daily_fire_2012_2020.csv.gz', index=False, compression='gzip')

In [62]:
!ls -la

total 378384
drwxr-xr-x@ 16 avkash  staff        512 Mar 26 13:29 .
drwxr-xr-x  12 avkash  staff        384 Mar 26 12:49 ..
-rw-r--r--@  1 avkash  staff       6148 Mar 26 10:30 .DS_Store
drwxr-xr-x   6 avkash  staff        192 Mar 26 10:03 .ipynb_checkpoints
-rw-r--r--   1 avkash  staff        623 Mar 26 12:47 README.md
-rw-r--r--   1 avkash  staff   14155994 Mar 26 13:25 ca_daily_fire_2000_2020.csv
-rw-r--r--   1 avkash  staff    3171046 Mar 26 13:25 ca_daily_fire_2012_2020.csv.gz
-rw-r--r--@  1 avkash  staff      25423 Mar 26 11:46 california.png
-rw-r--r--   1 avkash  staff    2455258 Mar 26 13:29 nepal_daily_fire_2000_2020.csv
-rw-r--r--   1 avkash  staff       3823 Mar 26 13:01 show_wildfire_map.ipynb
-rw-r--r--   1 avkash  staff  109378508 Mar 26 13:19 usa_daily_fire_2000_2021.csv
-rw-r--r--   1 avkash  staff   26457612 Mar 26 13:18 usa_daily_fire_2000_2021.csv.gz
-rw-r--r--   1 avkash  staff   26656065 Mar 26 08:32 usa_daily_fire_2012_2021.csv.gz
-rw-r--r--   1 avkash  staff       4772 Mar 26 13:01 wildfire-view-matplotlib.ipynb
-rw-r--r--   1 avkash  staff     242821 Mar 26 13:28 wildfire_data_creation-nepal.ipynb
-rw-r--r--   1 avkash  staff     331286 Mar 26 13:26 wildfire_data_creation.ipynb